# Generated by Django 4.2.8 on 2024-07-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=50)),
                ("address", models.CharField(max_length=255)),
                ("contact", models.CharField(max_length=10)),
            ],
        ),
    ]
