# Generated by Django 4.2.8 on 2024-08-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="password",
            field=models.CharField(default=False, max_length=20),
        ),
    ]
