# Generated by Django 4.2.8 on 2024-08-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0002_employee_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="password",
            field=models.CharField(max_length=20),
        ),
    ]
