# Generated by Django 4.2.8 on 2024-08-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0004_employee_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="name",
            new_name="username",
        ),
    ]
